### ISSUE TITLE
Ship widget

### ISSUE THREAD

**Issue by gattusov** [vlad-dolhopolov/Spajesty#2]
Widget heading for all ships regardless of the ship class is the same and says "[1] Frigate". In my opinion it should display the most important title of the ship - it's actual displayable name. The class of the ship should be displayed somewhere else in the widget, because it's not that important - we can tell what class the ship belongs to by just looking at it.

**Comment by vlad-dolhopolov** [comment]
Moved ship class text label down to other stats, its called Text_shipclass_value. The header label is going be storing ship's name and the text label is called Text_shipname.
