### ISSUE TITLE
Handling colony building damage 

### ISSUE THREAD

**Issue by vlad-dolhopolov** [vlad-dolhopolov/Spajesty#23]
Implement colony passing damage received to one of the buildings + UI for repairing

**Comment by vlad-dolhopolov** [comment]
Damage should be dealt to a random building + decrease the amount of colonists

**Comment by gattusov** [comment]
- UI for repairing
- add effectiveness stst for buildings and implement a system for buildings to go out of order when damaged severely

**Comment by vlad-dolhopolov** [comment]
Added buttons for repairing
