### ISSUE TITLE
Universal values in building stats

### ISSUE THREAD

**Issue by gattusov** [vlad-dolhopolov/Spajesty#40]
Add a universal value(s) to building stats and use it in each bulding as that building needs.

**Comment by gattusov** [comment]
Make values in Medical Centre cutomizable.

**Comment by gattusov** [comment]
Should we keep individual parameters in every builing and fill them in on statup or should we only store these values in the vector in BuildingStats?

**Comment by vlad-dolhopolov** [comment]
Nah, we don't need them as variables in buildings, I suggest we expose these parameters via getters in building classes
