### ISSUE TITLE
Pausing the game causes problems

### ISSUE THREAD

**Issue by gattusov** [vlad-dolhopolov/Spajesty#8]
If you pause and unpause the game a collision between a ship and some projectile may be detected even when the ship is the only one in the level, nobody's shooting and there are no visible projectiles on the map. This collision may cause massive damage (100+ hit points).

**Comment by vlad-dolhopolov** [comment]
The problem might be around pause/unpause methods in ingamelayer class. Unpause reschedules all entity updates, however projectiles should be updating only when fired.

**Comment by gattusov** [comment]
The problem still exists even after the latest fix - now all projectiles update from the start of the game until it gets paused for the first time.

**Comment by gattusov** [comment]
Now projectiles  won't fly, they just float on the same spot after being fired.
